"""
Git Pusher — Commit and push successful changes back to the Android project repo.

Only runs after Evaluator confirms success.
Generates a structured commit message from the plan + coder summary.
"""

from __future__ import annotations
import subprocess
from pathlib import Path

from aadh.core.models import Plan, CoderOutput


class GitPushError(Exception):
    pass


def commit_and_push(
    project_path: Path,
    plan: Plan,
    coder_output: CoderOutput,
    branch: str | None = None,   # None = push to current branch
    remote: str = "origin",
) -> str:
    """
    Stage changed files, commit with a structured message, and push.
    Returns the commit SHA on success.
    Raises GitPushError on any failure.
    """
    def run(cmd: str, check: bool = True) -> subprocess.CompletedProcess:
        result = subprocess.run(
            cmd, shell=True, cwd=str(project_path),
            capture_output=True, text=True, encoding="utf-8",
        )
        if check and result.returncode != 0:
            raise GitPushError(
                f"Command failed: {cmd}\n"
                f"stdout: {result.stdout}\n"
                f"stderr: {result.stderr}"
            )
        return result

    # ── Verify this is a git repo ─────────────────────────────────────────────
    check = run("git rev-parse --is-inside-work-tree", check=False)
    if check.returncode != 0:
        raise GitPushError(f"{project_path} is not inside a git repository.")

    # ── Stage only the files the Coder touched ────────────────────────────────
    changed_files = [c.file_path for c in coder_output.changes]
    if not changed_files:
        raise GitPushError("No files were changed — nothing to commit.")

    for rel_path in changed_files:
        run(f'git add "{rel_path}"')

    # ── Build commit message ──────────────────────────────────────────────────
    file_list = "\n".join(f"  - {f}" for f in changed_files)
    criteria  = "\n".join(f"  - {c}" for c in plan.acceptance_criteria[:5])
    msg = (
        f"feat: {plan.task}\n"
        f"\n"
        f"Changed files:\n{file_list}\n"
        f"\n"
        f"Acceptance criteria:\n{criteria}\n"
        f"\n"
        f"{coder_output.change_summary}\n"
        f"\n"
        f"Generated by AADH (Android Auto Dev Harness)"
    )

    run(f'git commit -m {_shell_quote(msg)}')

    # ── Get SHA ───────────────────────────────────────────────────────────────
    sha = run("git rev-parse HEAD").stdout.strip()

    # ── Push ──────────────────────────────────────────────────────────────────
    push_target = f"{remote} {branch}" if branch else remote
    run(f"git push {push_target}")

    return sha


def _shell_quote(s: str) -> str:
    """Single-quote a string for shell use."""
    return "'" + s.replace("'", "'\\''") + "'"
